### ISSUE TITLE
Play Framework SSO AD Get logged in user

### ISSUE THREAD

**Issue by sirhallt** [SlyngDK/play-module-ad-sso#3]
I have successfully implemented this module in my PLay app.  Thank you for creating this! However, I cannot figure out how to get the user after login is successful.  Can you provide instruction how to get the user information after successful login.

**Comment by SlyngDK** [comment]
You only get the username, when the user logging in( void userLoggedIn(String username)). For later use of the username, you have to keep it with the user session.

**Comment by sirhallt** [comment]
So when does that userLoggedIn get called and how would I reference in the Controller to store the user in the session?

Thank you very much for your assistance!
-Tom

**Comment by SlyngDK** [comment]
Have you taked a look at the sample [https://github.com/SlyngDK/play-module-ad-sso/blob/master/sample/app/controllers/Login.java](https://github.com/SlyngDK/play-module-ad-sso/blob/master/sample/app/controllers/Login.java)

The userLoggedIn is called when the negotiation(Kerberos login), is successful.
